#!/bin/bash
#
#see skript kontrollib kas arv on paaris või paaritu
#
#
if [ -z "$1" ]; then
	echo "Sisesta oma arv niimoodi: $0 arv"
#Kontrollib kas kasutaja on midagi sisestanud ja annab errori kui ei ole
else
	tehe=$(( $1 % 2 ))
if [ $tehe -eq 0 ]; then
#kontrollib arvu jääki peale kahega jagamist

	echo "$1 on paaris" 
else
	echo "$1 on paaritu"
fi
fi
#väljundab vastuse vastavalt jäägile.
#lõpp
