#!/bin/bash
#
#See skript laseb kasutjal arvutada küpsise pakkide arvu küpsise tordi jaoks
#
echo "Sisesta kandiku laius cm-tes :" #küsib kasutajalt infot
read kandikulaius #loeb kasutaja vastust ja lisab sellel väärtuse
echo "Sisesta kandiku pikkus cm-tes :"
read kandikupikkus
echo "Sisesta küpsise laius cm-tes :"
read kupalaius
echo "Sisesta küpsise pikkus cm-tes :"
read kupapikkus
echo "Sisesta soovitud küpsise kihtide arv :"
read kihtidearv
echo "sisesta mitu küpsist on ühes pakkis :"
read pakkid
kp=`expr $kandikulaius \* $kandikupikkus` #arvutab kandiku pindala ja lisab vastusele väärtuse
kpp=`expr $kupalaius \* $kupapikkus` #arvutab küpise pindala ja lisab vastusele väärtuse
ks=`expr $kp / $kpp` #arvutab 1 kihi jaoks valjalike küpsiste arvu
kk=`expr $ks \* $kihtidearv` #arvutab  kui palju küpiseid on vaja kogu tordi jaoks
sum=`expr $kk / $pakkid` #arvutab kui mitu küpsise pakki on vaja


jaakkihis=`expr $kp % $kpp` #arvutab kihi jäägi kui küpsis on suurem kui kandik
echo "jaakkihis "$jaakkihis
jaakkokku=`expr $jaakkihis \* $kihtidearv` #arvutab kõikide kihtide jäägi
echo "jaakkokku "$jaakkokku
kupaveel=`expr $jaakkokku / $kpp` #jäägi ja küpsiste pindala summa
echo "kupaveel "$kupaveel
kypsis=`expr $ks \* $kihtidearv` #kogu tordi jaoks minevate küpsiste arv
echo "kypsis "$kypsis
kokku=`expr $kypsis + $kupaveel` #küpsised ja jäägi arv
echo "kokku "$kokku
pakkis=`expr $kokku / $pakkid` #
echo "pakkis "$pakkis
jaak=`expr $kokku % $pakkid` #
echo "jaak "$jaak
echo "vaja on "$pakkis" pakki küpsist ja " $jaak" ja lisa pakki"
echo "kui siin ei ole null: "$jaakkokku" on 1 pakki juurde vaja"
#väljundab vaja minevate küpise pakkide arvu
#skripti lõpp
