#!/bin/bash
#
#See skript väljastab tärne
#
echo "Sisesta ridade arv"
read rida
#küsib kasutajalt ridade arvu
for (( i = $rida ; i >=1; i-- ))
do
	for (( j = 1 ;j <=$rida; j++ ))
	do
#lisab 1 kuni arvud on võrdsed kasutaja omadega, et saada read ja veerud
if [ $i -gt $j ]; then
		echo -n "o"
else
echo -n "*"
#prindib * ainult kui ridade arv on suurem kui veergude arv
fi
	done
echo ""
done
#skripti lõpp
